# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa032968030ee98280e46f581edd75a7201a151f23bedc329e55f1b1af8c7b5457e768dd0a154ed6f1f2566a0ce4d8d92a53dbf64376a6aced5bc9379e4c09c6

test:
  secret_key_base: 1c0a574f3a900543d3baa517c47dff54fe0efe34f7d85e4446a937d9f99ab5520872031b70c286503c655ffe4bf45faad167380c85e29d6353ba669a2e9a847f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
